Sekcja C i pierwszy rozdział.
olimpiada/kurs-oi pull request #11
Opened 2024-10-19 18:57 UTC by lduraj

2025-01-04 10:19 UTC, greg19 requested changes

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +Zalecamy w tym zadaniu pamiętac o dwóch rzeczach:
```suggestion
Zalecamy w tym zadaniu pamiętać o dwóch rzeczach:
```
Literówka

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +wystarczy nam zatem wiedzieć, że suma jest równa jest $\log \log N$ (logarytmowi z logarytmu z $N$), pomnożonemu przez pewną stałą.
```suggestion
wystarczy nam zatem wiedzieć, że suma jest równa $\log \log N$ (logarytmowi z logarytmu z $N$), pomnożonemu przez pewną stałą.
```
Powtórzenie

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +znajdzie pewnego dnia istotnie szybszych algorytmów rozkładu na czynniki, można przyjąć, że szyfrowanie tą metoda jest bezpieczne. Ze względu na to, jak
```suggestion
znajdzie pewnego dnia istotnie szybszych algorytmów rozkładu na czynniki, można przyjąć, że szyfrowanie tą metodą jest bezpieczne. Ze względu na to, jak
```
Literówka

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +W zadaniu o szybkim potęgowaniu na lekcji 2 należało obliczyć wynik pewnego działania ale wystarczyło podać jego cztery ostatnie cyfry, czyli resztę z
```suggestion
W zadaniu o szybkim potęgowaniu na lekcji 2 należało obliczyć wynik pewnego działania, ale wystarczyło podać jego cztery ostatnie cyfry, czyli resztę z
```
Przecinek przed "ale"

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +}
W reszcie kursu używamy nawiasów klamrowych w stylu K&R (w tej samej linii).

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +
```suggestion
```
Zbędna nowa linia

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +        cout << i;
```suggestion
        cout << i << '\n';
```
Ewentualnie `endl` albo `' '`.

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +     return true;                      // jeśli nie ma małych dzielników, to nie ma żadnych
```suggestion
    return true;                       // jeśli nie ma małych dzielników, to nie ma żadnych
```
O jedna spacja za dużo

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +Teraz bierzemy najmniejszą liczbę, której (3), wykreślamy wszystkie jej wielokrotności, i powtarzamy operację, dopóki to możliwe. Niewykreślone liczby, które rozpatrywaliśmy po drodze (2, 3, 5, ...)
"[...], której (3), [...]"
Coś tu się popsuło

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +Teraz bierzemy najmniejszą liczbę, której (3), wykreślamy wszystkie jej wielokrotności, i powtarzamy operację, dopóki to możliwe. Niewykreślone liczby, które rozpatrywaliśmy po drodze (2, 3, 5, ...)
Lepiej bezpośrednio:
"dopóki to możliwe" -> "dopóki są jeszcze niewykreślone liczby"
Tylko trzeba uważać na powtórzenie w następnym zdaniu

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +Teraz bierzemy najmniejszą liczbę, której (3), wykreślamy wszystkie jej wielokrotności, i powtarzamy operację, dopóki to możliwe. Niewykreślone liczby, które rozpatrywaliśmy po drodze (2, 3, 5, ...)
Myślę że warto napisać coś w stylu "Następną rozpatrywaną liczbą byłoby 5, jako że liczba 4 została wykreślona gdy usuwaliśmy wielokrotności liczby 2". Na razie wszystkie liczby które braliśmy to były po prostu kolejne liczby i nie napotkaliśmy żadnej wykreślonej.

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +danych bardzo małą liczbą (na przykład dla $N = 10^{82}$, szacowanej liczby cząstek we Wszechświecie, $\log \log N$ wciąż jest mniejszy od 9).
```suggestion
danych bardzo małą liczbą (na przykład dla $N = 10^{82}$ – szacowanej liczby cząstek we Wszechświecie – $\log \log N$ wciąż jest mniejszy od 9).
```
Myślę że tu lepiej użyć mocniejszego wtrącenia aby lepiej je oddzielić od reszty zdania

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +  momencie na pewno nie jest parzysta – ani przez 6.
```suggestion
  Teraz mamy pewność, że nie uda się podzielić przez 4 ani przez 6 – liczba w tym
  momencie na pewno nie jest parzysta.
```
Jakoś to wtrącenie dziwnie rozbija to zdanie

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +```
W reszcie kursu używamy nawiasów klamrowych w stylu K&R (w tej samej linii).

Poza tym stosowałbym regułę, że jeżeli konstrukcja wewnętrzna (w tym przypadku `if`) posiada klamry, to nie pomijamy klamer w konstrukcji zewnętrznej (w tym przypadku `for`), bo to dziwnie wygląda.

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +[algorytmem RSA](http://pl.wikipedia.org/wiki/RSA_(kryptografia) "Algorytm RSA - Wikipedia"), opiera się bardzo istotnie na
```suggestion
[algorytmem RSA](http://pl.wikipedia.org/wiki/RSA_(kryptografia) "Algorytm RSA - Wikipedia"), bardzo mocno opiera się na
```
Dziwnie mi brzmi sformułowanie "opierać się istotnie na czymś"

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +W algorytmie tym wybiera się bardzo duże (na przykład mające po kilka setek _cyfr_) liczby pierwsze $p$ oraz
```suggestion
W algorytmie tym wybiera się bardzo duże (na przykład mające po kilkaset _cyfr_) liczby pierwsze $p$ oraz
```
Prościej

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +szeroko ten algorytm jest stosowany, dobrze byłoby, gdyby rzeczywiście problem rozkładu na czynniki okazał się niemożliwy do szybkiego pokonania. Jak dotąd, nie mamy jednak takiej pewności.
Może warto tu jako ciekawostkę wspomnieć o komputerach kwantowych?

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +Ciekawostką jest fakt, że bardzo podobny problem sprawdzania pierwszości liczby, który dla nas był równie trudny, daje się rozwiązać znacznie bardziej efektywnie. Od dawna znane były algorytmy probab
```suggestion
Ciekawostką jest fakt, że bardzo podobny problem sprawdzania pierwszości liczby, który był tu dla nas równie trudny, daje się rozwiązać znacznie bardziej efektywnie. Od dawna znane były algorytmy probabilistyczne (takie, które dawały dobry wynik z bardzo dużą szansą, tym większą, im dłużej działały), a w 2002 roku trzech naukowców z Indii podało pierwszy deterministyczny (czyli "klasyczny") algorytm, który szybko sprawdza pierwszość.
```
Ja na początku myślałem że "nas" jako ludzkości, dlatego dodałbym słowo "tu" czy coś innego wskazującego że chodzi o autora i czytelnika

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +możemy zamiast tego domnażać wynik po kolei przez każdą liczbę oddzielnie, i po każdej operacji brać resztę z dzielenia. Innymi słowy, możemy wyobrażać sobie,
```suggestion
możemy zamiast tego domnażać do wyniku po kolei każdą liczbę oddzielnie, i po każdej operacji brać resztę z dzielenia. Innymi słowy, możemy wyobrażać sobie,
```
Pomijając to że słowo "domnażać" w ogóle nie istnieje i nie ma reguł z nim związanych, to wydaje mi się że poprawnie powinno być "domnażać coś do czegoś" a nie "domnażać coś przez coś".

Fajnie by było użyć jakiegoś słowa które istnieje w języku polskim, ale ja nie mam pomysłu jak lepiej napisać to zdanie, więc jestem OK z po prostu taką zmianą.

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +ale tej własności nie używaliśmy): jeśli na przykład chcemy pomnożyć przez siebie wiele liczb i znaleźć resztę z dzielenia iloczynu przez jakieś $M$,
```suggestion
ale tej własności nie używaliśmy): jeśli na przykład chcemy pomnożyć przez siebie wiele liczb i znaleźć resztę z dzielenia iloczynu przez $M$,
```
Niepotrzebne

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +resztę 1 z dzielenia przez $M$. A zatem można przyjąć po prostu $b' = b^{M-2}$ i obliczyć tę ostatnią potęgę za pomocą znanego z
Rozumiem, że nie można powiedzieć "możemy przyjąć $b^{-1} = \ldots$", bo nie "przyjmujemy" wartości odwrotności (tylko ona po prostu "jest"), ale ten prim jest tu tak trochę znikąd i nie wiadomo o co z tym $b'$ chodzi

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +Warto wspomnieć jeszcze, że istnieje algorytm, oparty na algorytmie Euklidesa, który pozwala szukać odwrotności również wtedy, jeśli $M$ nie jest liczbą pierwszą – wystarczy, aby odwracana reszta $b$
```suggestion
Warto wspomnieć jeszcze, że istnieje algorytm, oparty na algorytmie Euklidesa (zwany _rozszerzonym algorytmem Euklidesa_), który pozwala szukać odwrotności również wtedy, jeśli $M$ nie jest liczbą pierwszą – wystarczy, aby odwracana reszta $b$ nie miała wspólnego dzielnika z $M$.
```
Dziwnie brzmi to ostatnie zdanie

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +Bardzo łatwo napisać program znajdujący (i, na przykład, wypisujący na wyjście) wszystkie dzielniki zadanej liczby `n`:
```suggestion
Bardzo łatwo napisać kod znajdujący wszystkie dzielniki zadanej liczby `n`:
```
To wtrącenie nic nie wnosi. Myślę że czytelnik jest na tyle inteligentny, że ogarnie że wypisywanie to tylko przykład.

Poza tym to nie jest pełny (kompilujący się) "program" w C++.

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +for(int i = 1; i <= n; i++)
```suggestion
for (int i = 1; i <= n; i++)
```
W reszcie kursu po `for`, `if` itp wstawialiśmy spacje.

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +for(int i = 1; i * i <= n; i++)
```suggestion
for (int i = 1; i * i <= n; i++)
```
W reszcie kursu po `for`, `if` itp wstawialiśmy spacje.

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +    for(int i = 2; i * i <= n; i++)
```suggestion
    for (int i = 2; i * i <= n; i++)
```
W reszcie kursu po for, if itp wstawialiśmy spacje.

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +for(int i = 2; i <= N; i++)
```suggestion
for (int i = 2; i <= N; i++)
```
W reszcie kursu po for, if itp wstawialiśmy spacje.

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +for(int i = 2; i <= N; i++)  // bierzemy kolejną liczbę i
```suggestion
for (int i = 2; i <= N; i++) // bierzemy kolejną liczbę i
```

2025-01-04 10:19 UTC, greg19 commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +        for(int j = 2 * i; j <= N; j = j + i)   // iterujemy się po wszystkich wielokrotnościach i
```suggestion
        for (int j = 2 * i; j <= N; j = j + i) // iterujemy się po wszystkich wielokrotnościach i
```

2025-01-08 19:05 UTC, lduraj commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +}
OK, wprowadzam.

2025-01-08 19:09 UTC, lduraj commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +Teraz bierzemy najmniejszą liczbę, której (3), wykreślamy wszystkie jej wielokrotności, i powtarzamy operację, dopóki to możliwe. Niewykreślone liczby, które rozpatrywaliśmy po drodze (2, 3, 5, ...)
Poprawiam.

2025-01-08 19:09 UTC, lduraj commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +Teraz bierzemy najmniejszą liczbę, której (3), wykreślamy wszystkie jej wielokrotności, i powtarzamy operację, dopóki to możliwe. Niewykreślone liczby, które rozpatrywaliśmy po drodze (2, 3, 5, ...)
To ogólnie jest zbyt skrótowe. Rozbuduję.

2025-01-08 19:09 UTC, lduraj commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +Teraz bierzemy najmniejszą liczbę, której (3), wykreślamy wszystkie jej wielokrotności, i powtarzamy operację, dopóki to możliwe. Niewykreślone liczby, które rozpatrywaliśmy po drodze (2, 3, 5, ...)
Jw., rozbuduję ten akapit.

2025-01-08 19:10 UTC, lduraj commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +```
Poprawiam.

2025-01-08 19:14 UTC, lduraj commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +szeroko ten algorytm jest stosowany, dobrze byłoby, gdyby rzeczywiście problem rozkładu na czynniki okazał się niemożliwy do szybkiego pokonania. Jak dotąd, nie mamy jednak takiej pewności.
OK.

2025-01-08 19:17 UTC, lduraj commented on docs/C-wiecej-algorytmiki/C5-pierwszosc-dzielniki.md
> +resztę 1 z dzielenia przez $M$. A zatem można przyjąć po prostu $b' = b^{M-2}$ i obliczyć tę ostatnią potęgę za pomocą znanego z
Poprawiam.

2025-01-08 19:44 UTC, merged