Poprawki sekcji o WSL
olimpiada/kurs-oi pull request #8
Opened 2024-10-09 14:07 UTC by j4b6ski

Trochę moich sugestii jak można rozwinąć sekcję o WSLu. Chociaż im więcej przy tym dłubię tym więcej zastanawiam się czy to jest faktycznie najlepsze podejście. Możliwe że warto byłoby dokładniej opisać różne alternatywy.
Nagrania są do lekkiej korekty, trzeba by też sprawdzić instrukcje na świeżym Windowsie.

2025-01-05 00:09 UTC, blazejosinski commented
Jeżeli jest taka możliwość to prosiłbym o zaakceptowanie tych zmian. Kurs wisi online i jest trochę mylący - sam straciłem dość dużo czasu próbując przez niego przebrnąć pomagając aspirującemu olimpijczykowi z rodziny (na co dzień w ogóle nie używam Windowsa).
Jeżeli "nagrania są do lekkiej korekty" to nawet jeżeli nie ma czasu ich nagrywać ponownie to miałoby sens dodać tekstowy komentarz mówiący co trzeba zrobić inaczej.

CC @lduraj @tonowak
Przy okazji dziękuję za przygotowanie tych materiałów, są pomocne!

2025-01-05 10:55 UTC, tonowak commented
@blazejosinski dzięki za uwagi, zerkniemy na to wkrótce.

2025-01-07 11:51 UTC, j4b6ski reviewed
W myśl utrzymywania otwartej dyskusji dodałem trochę komentarzy czemu konkretnie uczepiłem się tam gdzie się uczepiłem.
Nie jestem przywiązany do konkretnych sformułowań które napisałem - tak jak zauważyłeś @greg19, sporo z nich jest zbyt skomplikowanych.
Natomiast chętnie dowiedziałbym się co myślisz na temat tych komentarzy.

2025-01-07 11:51 UTC, j4b6ski commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> -To tak naprawdę sposób uruchomienia *Linux*a, w którym łatwo się instaluje narzędzia dla programistów (z tego też powodu wiele zaawansowanych programistów korzysta z Linuxa zamiast Windowsa).
Spotkałem się wielokrotnie z komentarzami dotyczącymi "czy instalacja Linuxa nie popsuje mojego Windowsa" - jakaś wzmianka na ten temat jednak powinna się tu znaleźć

2025-01-07 11:51 UTC, j4b6ski commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +Jeśli powyższa metoda nie powiedzie się, należy spróbować starszego sposobu instalacji krok po kroku opisanego na stronie [learn.microsoft.com/windows/wsl/install-manual](https://learn.microsoft.com/
Myślę że jakieś odniesienie do oficjalnych instrukcji troubleshootingu jednak powinno się tu znaleźć. Zawsze znajdzie się ktoś komu nie zadziała, nawet jeśli nie będzie to przydatne dla potencjalnego uczestnika to może będzie jeśli poprosi kogoś o pomoc.

2025-01-07 11:51 UTC, j4b6ski commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +WSL jest oficjalnym oprogramowaniem od Microsoftu. Jego instalacja na nowszych komputerach jest bardzo prosta:
Instalacja WSL jednak ingeruje w system trochę bardziej niż zwykłego software'u - warto co najmniej wspomnieć, że nie instalujemy jakiegoś dziwnego czegoś od nie wiadomo kogo.

2025-01-07 11:51 UTC, j4b6ski commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> -Alternatywnie, można zainstalować kompilator MinGW do C++, ale wymaga to więcej kroków instalacyjnych.
"kompilator mingw" (co jest trochę mylnym nadużyciem, ale faktycznie ciężko to lepiej opisać bez wchodzenia w detale techniczne) jest zaskakująco trudny do zainstalowania - to zdanie jest zupełnie nieprzydatne dla początkujących (zobacz komentarz poniżej).

2025-01-07 11:51 UTC, j4b6ski commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +VSCode należy skonfigurować tak, żeby [połączył się z WSLem i używał go do kompilowania i uruchamiania programów w C++](https://code.visualstudio.com/docs/remote/wsl).
Uważam że jednak warto powiedzieć po co instalowaliśmy WSL i dlaczego to działa ze środowiskiem na windowsie.

Moja wzmianka o tym że "zastanawiam się czy to jest faktycznie najlepsze podejście" dotyczyła konkretnie tego punktu - skoro i tak korzystamy z IDE na windowsie to może zamiast instalować WSL na siłę to lepiej faktycznie pokierować jak zainstalować MinGW.

WSL jest szalenie użyteczny, ale może jest to zbyt dużo za szybko.

2025-01-07 11:51 UTC, j4b6ski commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +Jeśli instalacja WSL nie powiedzie się, alternatywnie można zainstalować kompilator GCC w wersji Windowsowej, na przykład dostarczony przez projekt [MinGW-w64](https://www.mingw-w64.org/). Nie istnie
Tutaj jest widoczny problem z MinGW - raz że trzeba wiedzieć który projekt jest aktualny, dwa że trzeba wiedzieć co dokładnie zainstalować. Polecam spróbować przejść samodzielnie przez ten proces, żeby przekonać się jak bardzo nieoczywiste to jest. Można by oczywiście ustalić jakąś konkretną opcję do zasugerowania uczestnikom. Kiedyś instalowało się Code::Blocks który był zpaczkowany z MinGW i nie było takich problemów.

2025-01-07 11:51 UTC, j4b6ski commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +W ostateczności jeśli zawiodą wszystkie inne opcje, można skorzystać ze środowiska online, na przykład [ide.usaco.guide](https://ide.usaco.guide/). Zalecamy jednak unikanie tej opcji o ile jest to mo
To jest świetna opcja która powinna pojawić się w kursie, co najmniej pod kątem osób które nie mają możliwości instalacj software'u w swoim komputerze. Z doświadczenia powiem że bardzo dużo początkujących osób korzysta faktycznie ze środowisk online - często ze sporo gorszych niż usaco.

2025-01-07 11:51 UTC, j4b6ski commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +<!-- TODO: poprawić na uruchamianie przez skrót, lub polecenie `wsl`
Poprawiony filmik wygląda super. Apeluję jednak żeby instrukcje zawrzeć także w formie tekstowej - jeśli przeszkadza wam "ściana tekstu" to można spróbować zrobić rozwijalną sekcję. Dzieci mają obecnie bardzo krótki attention span i filmiki w tutorialach potrafią bardzo odstraszać.

2025-01-07 11:51 UTC, j4b6ski commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +Geany należy skonfigurować tak, by kompilował i uruchamiał programy poprzez wywołanie polecenia `wsl`.
Jak wyżej do VSCode - co ustawiamy i po co?

2025-01-07 13:47 UTC, greg19 requested changes
Ja bym poklasyfikował czytelników tej lekcji na dwie grupy: taką która coś już sama programowała i taką, która nie.

Pierwsza grupa potrzebuje jak najprostszego wytłumaczenia – trudne słowa takie jak "maszyna wirtualna" albo "terminal" będą ich odstraszać. Taka osoba – która wchodzi na pierwszą lekcję programowania celem napisania Hello World – może się czuć że jest głupia, jeżeli nie będzie rozumieć 30% objętości tekstu. Dla niektórych może to być nawet na tyle zniechęcające, że pomyślą że programowanie nie jest dla nich i zrezygnują z takiej ścieżki kariery – nawet jeżeli są to nieliczne przypadki, nadal warto o nich myśleć.

Druga grupa (jeżeli w ogóle będzie przechodzić przez ten tutorial) pewnie będzie bardziej ogarnięta technologicznie, więc nie potrzebuje jakiś obszernych wyjaśnień. Jak będą potrzebować, to raczej będą w stanie sami znaleźć odpowiedź na swoje problemy.

Jeżeli tutorial będzie napisany jak dla osoby mniej ogarniętej niż ta która faktycznie go czyta, to nic się nie stanie. Jak będzie na odwrót, to już może mieć negatywne skutki. W związku z tym uważam że akurat ta część kursu powinna być szczególnie jak najprostsza.

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +Jeśli powyższa metoda nie powiedzie się, należy spróbować starszego sposobu instalacji krok po kroku opisanego na stronie [learn.microsoft.com/windows/wsl/install-manual](https://learn.microsoft.com/
Link do oficjalnej instrukcji brzmi git (ten pierwszy). Jednak nie jestem przekonany że osobie której nie uda się przejść przez pierwszy link uda się przejść przez drugi. Z tym linkiem do troubleshootingu mam podobne odczucie, ale może rzeczywiście jest w nim jakaś wartość.

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +Z WSLa korzystamy najpierw uruchamiając go skrótem `WSL` lub `Ubuntu`. Zadziała także polecenie `wsl` w oknie `cmd` lub `PowerShell`. Powinien uruchomić się *terminal* Linuxa, którego poprawne działa
Na pewno nie używałbym słów "terminal" i nie wspominał o `uname` – są zbyt straszne. Wpisywanie `wsl` w prompt też brzmi jak coś co nie będzie przydatne piętnastolatkowi.

Co do wspomnieniu o samym odpaleniu terminala, my pokazujemy setup w którym nie jest to potrzebne. Dociekliwy czytelnik, który chce zrobić coś więcej niż w naszych filmikach, raczej ogarnie że to się tak robi i nie trzeba tym nieogarniętym dodawać dodatkowego tekstu do sparsowania.

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +Jeśli instalacja WSL nie powiedzie się, alternatywnie można zainstalować kompilator GCC w wersji Windowsowej, na przykład dostarczony przez projekt [MinGW-w64](https://www.mingw-w64.org/). Nie istnie
Nie jestem przekonany, że osobie której nie uda się zainstalować WSL uda się przejść przez ten proces. Myślę że jeżeli "instalacja WSL się nie powiedzie" to należy spróbować ponownie/inaczej, a nie zaczynać od nowa czegoś jeszcze trudniejszego.

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +W ostateczności jeśli zawiodą wszystkie inne opcje, można skorzystać ze środowiska online, na przykład [ide.usaco.guide](https://ide.usaco.guide/). Zalecamy jednak unikanie tej opcji o ile jest to mo
Wspomnienie o kompilatorach online brzmi jak dobry pomysł. Chociaż nie używałbym w tym momencie kursu słów "testowanie losowego rozwiązania". Wywaliłbym drugie zdanie. Pierwsze zdanie i tak zaczyna się od "w ostateczności", więc widać że nie polecamy tej opcji.

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +Geany należy skonfigurować tak, by kompilował i uruchamiał programy poprzez wywołanie polecenia `wsl`.
Ditto

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +VSCode należy skonfigurować tak, żeby [połączył się z WSLem i używał go do kompilowania i uruchamiania programów w C++](https://code.visualstudio.com/docs/remote/wsl).
Według mnie sekcje "Wstęp" i "Środowisko programistyczne C++" już wystarczająco dobrze wyjaśniają o co chodzi.

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +<!-- TODO: poprawić na uruchamianie przez skrót, lub polecenie `wsl`
Myślę że same komendy to dobry pomysł, żeby nie musieć przepisywać.

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> -Alternatywnie, można zainstalować kompilator MinGW do C++, ale wymaga to więcej kroków instalacyjnych.
Myślę że podobnej długości zdanie powinno się znaleźć w sekcji "alternatywy". W moim odczuciu targetuje ono osoby które są bardziej ogarnięte i z jakiegoś powodu nie chcą korzystać z WSL. Oni potrzebują jedynie jakiegoś punktu zaczepienia, żeby wiedzieć co googlować, a nie konkretnych instrukcji. Tych mniej ogarniętych według mnie należy przekonywać do WSL.

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +WSL jest oficjalnym oprogramowaniem od Microsoftu. Jego instalacja na nowszych komputerach jest bardzo prosta:
Myślę że osób które podążają za tym tutorialem raczej nie obchodzi to jak bardzo coś ingeruje w ich komputer. Patrz instalowanie sobie rootkita żeby pograć w LoLa.

Samo pierwsze zdanie jest na tyle krótkie że uważam że można zostawić, tylko może tam wyżej gdzie jest pierwsza wzmianka o WSL.

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> -To tak naprawdę sposób uruchomienia *Linux*a, w którym łatwo się instaluje narzędzia dla programistów (z tego też powodu wiele zaawansowanych programistów korzysta z Linuxa zamiast Windowsa).
Może wystarczy dodać "sposób uruchomienia Linuxa na Windowsie", albo coś w tym stylu.

Nie używałbym słów "maszyna wirtualna" i "system plików" – są zbyt straszne. Cały fragment "i dobrze zintegrowana z Windowsowym systemem plików i wyświetlaniem okienek" według mnie nie jest potrzebny. Zdanie "Dzięki temu..." też na razie wygląda mi niepotrzebnie, myślę że można się obejść bez niego i dodać tylko kilka słów przy definicji WSL.

Tutaj można wspomnieć że WSL jest oficjalnym oprogramowaniem od Microsoft.

2025-01-07 13:47 UTC, greg19 commented on docs/A-podstawy-programowania/A1-pierwszy-program.md
> +Program `g++` jest wersją kompilatora [GCC](https://gcc.gnu.org/) używającą C++ jako domyślny język.
Zbyt techniczne

2026-03-17 12:30 UTC, j4b6ski commented
Zamykam, bo od dawna nie znalazłem czasu się tym zająć, i nie planuję do tego w tym momencie wracać.
W razie czego jeśli ktoś by do tego wracał to możecie tego co napisałem śmiało użyć jako inspirację albo antyinspirację.
Dla mnie tu była trudna kwestia znalezienia równowagi pomiędzy za małą ilością informacji żeby debugować problemy, a za dużą ilością detali dla grupy docelowej.

2026-03-17 12:30 UTC, closed without merging